<?
$aMenuLinks = Array(
    Array(
        "О компании",
        "company/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Отзывы",
        "news/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Руководство",
        "products/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Миссия и стратегия",
        "photo/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "История",
        "partners/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Вакансии",
        "contacts/",
        Array(),
        Array(),
        ""
    )
);
?>